âœ chore: profile:
  - changed-files:
      - any-glob-to-any-file: src/profile/*

"invalid":
  - "data/**"

tests:
  - "tests/**"

storybook:
  - "stories/**"

dependencies:
  - "package.*"

"CI/CD":
  - ".github/**"

"ğŸ“– docs":
  - "pages/docs/**"

"models":
  - "models/**"
